### ISSUE TITLE
Support all "Unknown" DNS Resource Record (RR) Types

### ISSUE THREAD

**Issue by jeroenvermeulen** [exonet/powerdns-php#135]
I created this issue to replace PR #133. As @robbinjanssen suggests a solution is needed to support all "Unknown" DNS Resource Record (RR) Types.

**Describe the bug**
The record type TYPE65534 appears in PowerDNS in some zones we are slave for.
When loading such a zone Exonet PowerDNS throws exception:
```
PHP Fatal error:  Uncaught Exonet\Powerdns\Exceptions\InvalidRecordType: The record type [TYPE65534] is not a valid DNS Record type. in .../vendor/exonet/powerdns-php/src/Resources/ResourceRecord.php:387
```

**To Reproduce**
```bash
pdnsutil  create-zone  trouble-xyz.com.
pdnsutil  add-record  trouble-xyz.com.  oh-no  TYPE65534  '\# 4 aabbccdd'
pdnsutil  list-zone  trouble-xyz.com.
```
Zone looks like this:
```
$ORIGIN .
oh-no.trouble-xyz.com	3600	IN	TYPE65534	\# 4 aabbccdd
trouble-xyz.com	3600	IN	SOA	ns1.provider.com support.provider.com 0 7200 900 1209600 86400
```
in PHP:
```php
<?php
require_once __DIR__ . "/vendor/autoload.php";
$exonetPowerdns = new ExonetPowerdns('nsmaster.provider.com', '___apiKey___', 8081);
$zone = $exonetPowerdns->zone('123-trouble-xyz.com.');
$zone->get();
```
Throws error:
```
PHP Fatal error:  Uncaught Exonet\Powerdns\Exceptions\InvalidRecordType: The record type [TYPE65534] is not a valid DNS Record type. in vendor/exonet/powerdns-php/src/Resources/ResourceRecord.php:387
Stack trace:
#0 vendor/exonet/powerdns-php/src/Resources/ResourceRecord.php(139): Exonet\Powerdns\Resources\ResourceRecord->setType('TYPE65534')
#1 vendor/exonet/powerdns-php/src/Helper.php(32): Exonet\Powerdns\Resources\ResourceRecord->setApiResponse(Array)
#2 vendor/exonet/powerdns-php/src/Resources/Zone.php(496): Exonet\Powerdns\Helper::createResourceRecord('123-trouble-xyz...', Array)
#3 vendor/exonet/powerdns-php/src/Resources/Zone.php(101): Exonet\Powerdns\Resources\Zone->setResourceRecords(Array)
#4 vendor/exonet/powerdns-php/src/AbstractZone.php(69): Exonet\Powerdns\Resources\Zone->setApiResponse(Array)
#5 vendor/exonet/powerdns-php/src/Zone.php(100): Exonet\Powerdns\AbstractZone->resource()
#6 test.php(5): Exonet\Powerdns\Zone->get()
#8 {main}
  thrown in vendor/exonet/powerdns-php/src/Resources/ResourceRecord.php on line 387
```

**Expected behavior**
Load the zone.

**Additional context**
On the bottom of the page:
https://doc.powerdns.com/authoritative/appendices/types.html#unknown-dns-resource-record-rr-types
There is a link to https://datatracker.ietf.org/doc/html/rfc3597.html

It has something to do with NSEC. I tried to find an official explanation but was not able to find it quickly. 
The fact is we have these records in our PowerDNS 4.7.4, and can't load these zones at the moment.

**Comment by jeroenvermeulen** [comment]
Found more info on the Type numbers of RRs:
https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-4
I suggest we support 65280-65534 (inclusive)
